POST http://localhost:8000/books/create/ HTTP/1.1
Content-Type: application/json

{
    "title": "The Hobbit",
    "author": "J.R.R. Tolkien",
    "publisher": "Houghton Mifflin",
    "publication_date": "1937-09-21",
    "isbn": "9780547928227",
    "genre": "Fantasy"
}
