# Generated by Django 4.1.7 on 2023-03-03 02:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d{13}$', 'ISBN must be 13 digits.')]),
        ),
    ]
